// Initial Seed Data for GameOps AI Data Pipelines Engine

import { Project, DataSource, Schema, Dataset, User, Team } from '@/types';
import { Pipeline, PipelineRun } from '@/types/pipeline';
import { ValidationRule, DataContract } from '@/types/quality';
import { SystemAlert, PipelineLogEntry, ProjectTask, AuditEvent } from '@/types/observability';
import { FeatureSet } from '@/types/ml';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_alex',
    name: 'Alex Vance',
    email: 'alex.vance@gameops.io',
    role: 'Data Engineer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    teamId: 'team_core',
  },
  {
    id: 'usr_sarah',
    name: 'Sarah Connor',
    email: 'sarah.c@gameops.io',
    role: 'Analytics Engineer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    teamId: 'team_core',
  },
  {
    id: 'usr_marcus',
    name: 'Marcus Brody',
    email: 'm.brody@gameops.io',
    role: 'ML Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    teamId: 'team_ml',
  },
  {
    id: 'usr_elena',
    name: 'Elena Rostova',
    email: 'elena.r@gameops.io',
    role: 'Game Analyst',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    teamId: 'team_analytics',
  },
];

export const INITIAL_TEAMS: Team[] = [
  { id: 'team_core', name: 'Data Platform Core', description: 'Pipeline infra and telemetry ingestion', memberIds: ['usr_alex', 'usr_sarah'], createdAt: '2026-01-15T08:00:00Z' },
  { id: 'team_ml', name: 'AI & ML Infrastructure', description: 'Feature store and model training datasets', memberIds: ['usr_marcus'], createdAt: '2026-02-01T09:30:00Z' },
  { id: 'team_analytics', name: 'LiveOps Analytics', description: 'Player telemetry and economy metrics', memberIds: ['usr_elena'], createdAt: '2026-02-10T10:00:00Z' },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj_telemetry',
    name: 'Game Telemetry & Events',
    description: 'High-frequency player telemetry events, session logs, and match activity ingestion',
    ownerId: 'usr_alex',
    teamId: 'team_core',
    environment: 'Production',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-08-30T14:22:00Z',
    tags: ['Telemetry', 'Gameplay', 'LiveOps'],
    dataSourceIds: ['src_events_stream', 'src_match_logs'],
    pipelineIds: ['pipe_telemetry_clean', 'pipe_session_agg'],
    datasetIds: ['ds_raw_telemetry', 'ds_clean_telemetry', 'ds_player_sessions'],
    metricCount: 14,
    alertCount: 2,
  },
  {
    id: 'proj_economy',
    name: 'Economy & Monetization',
    description: 'Microtransactions, gold sinks, loot boxes, and virtual currency transactions tracking',
    ownerId: 'usr_sarah',
    teamId: 'team_analytics',
    environment: 'Production',
    createdAt: '2026-03-10T11:00:00Z',
    updatedAt: '2026-08-31T09:15:00Z',
    tags: ['Economy', 'Monetization', 'Players'],
    dataSourceIds: ['src_purchase_logs'],
    pipelineIds: ['pipe_economy_analytics'],
    datasetIds: ['ds_purchases', 'ds_economy_daily'],
    metricCount: 8,
    alertCount: 0,
  },
  {
    id: 'proj_ai_training',
    name: 'AI Training Features',
    description: 'Player churn prediction features, bot NPC behavior dataset, and match balancing features',
    ownerId: 'usr_marcus',
    teamId: 'team_ml',
    environment: 'Staging',
    createdAt: '2026-04-05T15:00:00Z',
    updatedAt: '2026-08-29T16:40:00Z',
    tags: ['AI', 'ML', 'Features'],
    dataSourceIds: ['src_events_stream'],
    pipelineIds: ['pipe_ml_features'],
    datasetIds: ['ds_player_features', 'ds_churn_training'],
    metricCount: 6,
    alertCount: 1,
  },
];

export const INITIAL_DATA_SOURCES: DataSource[] = [
  {
    id: 'src_events_stream',
    projectId: 'proj_telemetry',
    name: 'Live Game Event Stream',
    type: 'Telemetry Stream',
    status: 'active',
    recordCount: 2450000,
    lastIngestionAt: '2026-08-31T20:40:00Z',
    frequency: 'Real-time (500/s)',
    ownerId: 'usr_alex',
    schemaId: 'sch_game_event',
    config: { streamRate: 500 },
    createdAt: '2026-03-01T10:30:00Z',
    updatedAt: '2026-08-31T20:40:00Z',
  },
  {
    id: 'src_match_logs',
    projectId: 'proj_telemetry',
    name: 'Match Server Logs (NDJSON)',
    type: 'NDJSON',
    status: 'active',
    recordCount: 890000,
    lastIngestionAt: '2026-08-31T20:30:00Z',
    frequency: 'Hourly',
    ownerId: 'usr_alex',
    schemaId: 'sch_match_data',
    config: { filePath: '/data/logs/matches_*.ndjson' },
    createdAt: '2026-03-05T12:00:00Z',
    updatedAt: '2026-08-31T20:30:00Z',
  },
  {
    id: 'src_purchase_logs',
    projectId: 'proj_economy',
    name: 'IAP Purchase Stream',
    type: 'JSON',
    status: 'active',
    recordCount: 125000,
    lastIngestionAt: '2026-08-31T20:35:00Z',
    frequency: 'Every 5 mins',
    ownerId: 'usr_sarah',
    schemaId: 'sch_purchase',
    config: { apiEndpoint: '/api/v1/ingest/purchases' },
    createdAt: '2026-03-12T09:00:00Z',
    updatedAt: '2026-08-31T20:35:00Z',
  },
];

export const INITIAL_SCHEMAS: Schema[] = [
  {
    id: 'sch_game_event',
    projectId: 'proj_telemetry',
    name: 'GameEventV2',
    version: 2,
    compatibility: 'Compatible',
    fields: [
      { name: 'event_id', type: 'String', required: true, nullable: false, description: 'UUID event identifier' },
      { name: 'event_name', type: 'String', required: true, nullable: false, description: 'Type of event (session_started, player_death, etc.)' },
      { name: 'timestamp', type: 'Datetime', required: true, nullable: false, description: 'UTC timestamp ISO8601' },
      { name: 'player_id', type: 'String', required: true, nullable: false, description: 'Unique player UUID' },
      { name: 'session_id', type: 'String', required: true, nullable: false, description: 'Game session UUID' },
      { name: 'level', type: 'Integer', required: false, nullable: true, constraints: { min: 1, max: 100 } },
      { name: 'platform', type: 'String', required: true, nullable: false },
      { name: 'region', type: 'String', required: true, nullable: false },
    ],
    changeHistory: [
      { version: 1, changedAt: '2026-03-01T10:00:00Z', changedBy: 'Alex Vance', changes: ['Initial schema creation'] },
      { version: 2, changedAt: '2026-06-15T14:30:00Z', changedBy: 'Alex Vance', changes: ['Added region field', 'Made level optional'] },
    ],
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-06-15T14:30:00Z',
  },
  {
    id: 'sch_purchase',
    projectId: 'proj_economy',
    name: 'IAPTransactionV1',
    version: 1,
    compatibility: 'Compatible',
    fields: [
      { name: 'transaction_id', type: 'String', required: true, nullable: false },
      { name: 'player_id', type: 'String', required: true, nullable: false },
      { name: 'amount', type: 'Float', required: true, nullable: false, constraints: { min: 0 } },
      { name: 'currency', type: 'String', required: true, nullable: false },
      { name: 'item_id', type: 'String', required: true, nullable: false },
      { name: 'timestamp', type: 'Datetime', required: true, nullable: false },
    ],
    changeHistory: [
      { version: 1, changedAt: '2026-03-10T11:00:00Z', changedBy: 'Sarah Connor', changes: ['Initial schema'] },
    ],
    createdAt: '2026-03-10T11:00:00Z',
    updatedAt: '2026-03-10T11:00:00Z',
  },
];

export const INITIAL_DATASETS: Dataset[] = [
  {
    id: 'ds_raw_telemetry',
    projectId: 'proj_telemetry',
    name: 'Raw Game Events',
    description: 'Unprocessed telemetry events streamed directly from game clients',
    ownerId: 'usr_alex',
    recordCount: 2450000,
    sizeBytes: 842000000, // ~842 MB
    columnCount: 8,
    schemaId: 'sch_game_event',
    qualityScore: 94.5,
    freshnessScore: 99.2,
    status: 'Healthy',
    domain: 'Telemetry',
    tags: ['Raw', 'Telemetry', 'Stream'],
    records: [
      { event_id: 'evt_101', event_name: 'session_started', timestamp: '2026-08-31T20:30:00Z', player_id: 'ply_8892', session_id: 'ses_9012', level: 12, platform: 'PC', region: 'NA-East' },
      { event_id: 'evt_102', event_name: 'player_death', timestamp: '2026-08-31T20:32:15Z', player_id: 'ply_8892', session_id: 'ses_9012', level: 12, platform: 'PC', region: 'NA-East' },
      { event_id: 'evt_103', event_name: 'match_completed', timestamp: '2026-08-31T20:40:00Z', player_id: 'ply_3341', session_id: 'ses_8811', level: 45, platform: 'PlayStation', region: 'EU-Central' },
    ],
    createdAt: '2026-03-01T10:30:00Z',
    updatedAt: '2026-08-31T20:40:00Z',
    lastRefreshedAt: '2026-08-31T20:40:00Z',
  },
  {
    id: 'ds_clean_telemetry',
    projectId: 'proj_telemetry',
    name: 'Curated Telemetry Events',
    description: 'Validated, deduplicated, and enriched telemetry events',
    ownerId: 'usr_alex',
    recordCount: 2420000,
    sizeBytes: 810000000,
    columnCount: 10,
    schemaId: 'sch_game_event',
    qualityScore: 99.8,
    freshnessScore: 98.5,
    status: 'Healthy',
    domain: 'Telemetry',
    tags: ['Curated', 'Clean', 'Enriched'],
    records: [
      { event_id: 'evt_101', event_name: 'session_started', timestamp: '2026-08-31T20:30:00Z', player_id: 'ply_8892', session_id: 'ses_9012', level: 12, platform: 'PC', region: 'NA-East', engagement_score: 8.4, country: 'USA' },
      { event_id: 'evt_102', event_name: 'player_death', timestamp: '2026-08-31T20:32:15Z', player_id: 'ply_8892', session_id: 'ses_9012', level: 12, platform: 'PC', region: 'NA-East', engagement_score: 8.4, country: 'USA' },
    ],
    createdAt: '2026-03-02T11:00:00Z',
    updatedAt: '2026-08-31T20:35:00Z',
    lastRefreshedAt: '2026-08-31T20:35:00Z',
  },
  {
    id: 'ds_player_sessions',
    projectId: 'proj_telemetry',
    name: 'Player Sessions Aggregates',
    description: 'Session duration, total matches, kills, and monetization metrics per player session',
    ownerId: 'usr_sarah',
    recordCount: 450000,
    sizeBytes: 156000000,
    columnCount: 12,
    schemaId: 'sch_game_event',
    qualityScore: 98.1,
    freshnessScore: 95.0,
    status: 'Healthy',
    domain: 'Gameplay',
    tags: ['Aggregated', 'Sessions'],
    records: [
      { session_id: 'ses_9012', player_id: 'ply_8892', start_time: '2026-08-31T20:00:00Z', end_time: '2026-08-31T20:45:00Z', duration_minutes: 45, matches_played: 3, total_kills: 14, total_deaths: 5, spend_usd: 9.99 },
    ],
    createdAt: '2026-03-10T14:00:00Z',
    updatedAt: '2026-08-31T20:00:00Z',
    lastRefreshedAt: '2026-08-31T20:00:00Z',
  },
];

export const INITIAL_PIPELINES: Pipeline[] = [
  {
    id: 'pipe_telemetry_clean',
    projectId: 'proj_telemetry',
    name: 'Raw Telemetry Ingestion & Cleaning',
    description: 'Parses raw game stream events, validates schema, filters corrupt payloads, enriches geo metadata, and writes to Curated Telemetry',
    version: 3,
    status: 'Published',
    schedule: 'Hourly',
    ownerId: 'usr_alex',
    environment: 'Production',
    cacheEnabled: true,
    retryPolicy: { maxRetries: 3, backoffMs: 1000 },
    parameters: [
      { name: 'batch_size', type: 'number', defaultValue: 5000, description: 'Number of records per worker batch' },
      { name: 'environment', type: 'string', defaultValue: 'Production', description: 'Target environment stage' },
    ],
    nodes: [
      { id: 'node_src', type: 'Source', label: 'Raw Event Stream', position: { x: 100, y: 150 }, config: { dataSourceId: 'src_events_stream' } },
      { id: 'node_parse', type: 'Parse', label: 'Parse JSON Payload', position: { x: 300, y: 150 }, config: {} },
      { id: 'node_validate', type: 'Validate', label: 'Schema Validation', position: { x: 500, y: 150 }, config: { schemaId: 'sch_game_event', strictMode: true } },
      { id: 'node_filter', type: 'Filter', label: 'Filter Null Players', position: { x: 700, y: 150 }, config: { field: 'player_id', operator: 'notNull' } },
      { id: 'node_enrich', type: 'Enrich', label: 'Enrich Geo & Device Metadata', position: { x: 900, y: 150 }, config: { enrichType: 'geo_ip' } },
      { id: 'node_out', type: 'Output', label: 'Save Curated Dataset', position: { x: 1100, y: 150 }, config: { datasetId: 'ds_clean_telemetry', outputName: 'Curated Telemetry' } },
    ],
    edges: [
      { id: 'edge_1', sourceNodeId: 'node_src', targetNodeId: 'node_parse' },
      { id: 'edge_2', sourceNodeId: 'node_parse', targetNodeId: 'node_validate' },
      { id: 'edge_3', sourceNodeId: 'node_validate', targetNodeId: 'node_filter' },
      { id: 'edge_4', sourceNodeId: 'node_filter', targetNodeId: 'node_enrich' },
      { id: 'edge_5', sourceNodeId: 'node_enrich', targetNodeId: 'node_out' },
    ],
    createdAt: '2026-03-01T11:00:00Z',
    updatedAt: '2026-08-30T16:00:00Z',
    lastRunAt: '2026-08-31T20:00:00Z',
    lastRunStatus: 'Succeeded',
  },
  {
    id: 'pipe_session_agg',
    projectId: 'proj_telemetry',
    name: 'Player Sessionization Pipeline',
    description: 'Calculates 1-hour tumbling window session metrics, aggregate kills, deaths, and playtime',
    version: 1,
    status: 'Published',
    schedule: 'Daily',
    ownerId: 'usr_sarah',
    environment: 'Production',
    cacheEnabled: true,
    retryPolicy: { maxRetries: 1, backoffMs: 2000 },
    parameters: [],
    nodes: [
      { id: 'node_src', type: 'Source', label: 'Curated Telemetry', position: { x: 100, y: 150 }, config: { datasetId: 'ds_clean_telemetry' } },
      { id: 'node_window', type: 'Window', label: '1-Hour Tumbling Window', position: { x: 350, y: 150 }, config: { windowType: 'tumbling', windowSizeMinutes: 60, timestampField: 'timestamp' } },
      { id: 'node_agg', type: 'Aggregate', label: 'Aggregate Session Metrics', position: { x: 600, y: 150 }, config: { groupBy: ['player_id', 'session_id'], metrics: [{ field: 'event_id', func: 'count', alias: 'total_events' }] } },
      { id: 'node_out', type: 'Output', label: 'Save Player Sessions', position: { x: 850, y: 150 }, config: { datasetId: 'ds_player_sessions', outputName: 'Player Sessions' } },
    ],
    edges: [
      { id: 'edge_1', sourceNodeId: 'node_src', targetNodeId: 'node_window' },
      { id: 'edge_2', sourceNodeId: 'node_window', targetNodeId: 'node_agg' },
      { id: 'edge_3', sourceNodeId: 'node_agg', targetNodeId: 'node_out' },
    ],
    createdAt: '2026-03-10T14:00:00Z',
    updatedAt: '2026-08-31T10:00:00Z',
    lastRunAt: '2026-08-31T18:00:00Z',
    lastRunStatus: 'Succeeded',
  },
];

export const INITIAL_PIPELINE_RUNS: PipelineRun[] = [
  {
    id: 'run_1001',
    pipelineId: 'pipe_telemetry_clean',
    pipelineName: 'Raw Telemetry Ingestion & Cleaning',
    projectId: 'proj_telemetry',
    version: 3,
    status: 'Succeeded',
    triggeredBy: 'Scheduler (Hourly)',
    parameters: { batch_size: 5000, environment: 'Production' },
    durationMs: 4250,
    recordsProcessed: 25000,
    qualityScore: 99.8,
    cacheHit: false,
    tasks: [
      { id: 'task_1', runId: 'run_1001', nodeId: 'node_src', nodeLabel: 'Raw Event Stream', nodeType: 'Source', status: 'Succeeded', recordsIn: 25000, recordsOut: 25000, durationMs: 400, startedAt: '2026-08-31T20:00:00Z', completedAt: '2026-08-31T20:00:00.4Z', logs: ['Connected to live telemetry buffer', 'Read 25,000 records'] },
      { id: 'task_2', runId: 'run_1001', nodeId: 'node_parse', nodeLabel: 'Parse JSON Payload', nodeType: 'Parse', status: 'Succeeded', recordsIn: 25000, recordsOut: 25000, durationMs: 850, startedAt: '2026-08-31T20:00:00.4Z', completedAt: '2026-08-31T20:00:01.2Z', logs: ['Parsed 25,000 valid JSON tokens'] },
      { id: 'task_3', runId: 'run_1001', nodeId: 'node_validate', nodeLabel: 'Schema Validation', nodeType: 'Validate', status: 'Succeeded', recordsIn: 25000, recordsOut: 24850, durationMs: 1200, startedAt: '2026-08-31T20:00:01.2Z', completedAt: '2026-08-31T20:00:02.4Z', logs: ['150 records failed schema check', 'Sent 150 records to Rejected Records store'] },
      { id: 'task_4', runId: 'run_1001', nodeId: 'node_filter', nodeLabel: 'Filter Null Players', nodeType: 'Filter', status: 'Succeeded', recordsIn: 24850, recordsOut: 24850, durationMs: 500, startedAt: '2026-08-31T20:00:02.4Z', completedAt: '2026-08-31T20:00:02.9Z', logs: ['Filter condition player_id IS NOT NULL passed for all records'] },
      { id: 'task_5', runId: 'run_1001', nodeId: 'node_enrich', nodeLabel: 'Enrich Geo Metadata', nodeType: 'Enrich', status: 'Succeeded', recordsIn: 24850, recordsOut: 24850, durationMs: 900, startedAt: '2026-08-31T20:00:02.9Z', completedAt: '2026-08-31T20:00:03.8Z', logs: ['Enriched 24,850 records with GeoIP and device info'] },
      { id: 'task_6', runId: 'run_1001', nodeId: 'node_out', nodeLabel: 'Save Curated Dataset', nodeType: 'Output', status: 'Succeeded', recordsIn: 24850, recordsOut: 24850, durationMs: 400, startedAt: '2026-08-31T20:00:03.8Z', completedAt: '2026-08-31T20:00:04.2Z', logs: ['Committed 24,850 records to Curated Telemetry dataset'] },
    ],
    startedAt: '2026-08-31T20:00:00Z',
    completedAt: '2026-08-31T20:00:04.25Z',
  },
];

export const INITIAL_ALERTS: SystemAlert[] = [
  {
    id: 'alt_101',
    ruleId: 'rule_freshness_check',
    ruleName: 'Telemetry Freshness Exceeded',
    projectId: 'proj_telemetry',
    severity: 'warning',
    title: 'Match Server Logs Delayed',
    message: 'Ingestion freshness score dropped to 82%. Expected < 15 mins delay, actual delay 22 mins.',
    targetName: 'Match Server Logs (NDJSON)',
    triggeredAt: '2026-08-31T19:45:00Z',
    status: 'active',
  },
  {
    id: 'alt_102',
    ruleId: 'rule_schema_drift',
    ruleName: 'Schema Drift Warning',
    projectId: 'proj_telemetry',
    severity: 'info',
    title: 'New Optional Field Detected',
    message: 'New field "weapon_skin_id" detected in live stream event payload.',
    targetName: 'Live Game Event Stream',
    triggeredAt: '2026-08-31T18:10:00Z',
    status: 'acknowledged',
  },
];

export const INITIAL_LOGS: PipelineLogEntry[] = [
  { id: 'log_1', timestamp: '2026-08-31T20:40:12Z', pipelineId: 'pipe_telemetry_clean', pipelineName: 'Raw Telemetry Ingestion & Cleaning', runId: 'run_1001', level: 'INFO', message: 'Batch run completed successfully. 24,850 records processed in 4,250ms.' },
  { id: 'log_2', timestamp: '2026-08-31T20:35:05Z', pipelineId: 'pipe_telemetry_clean', pipelineName: 'Raw Telemetry Ingestion & Cleaning', runId: 'run_1001', level: 'WARN', message: '150 invalid records routed to Dead Letter Store due to null timestamp.' },
  { id: 'log_3', timestamp: '2026-08-31T20:30:00Z', pipelineId: 'pipe_telemetry_clean', pipelineName: 'Raw Telemetry Ingestion & Cleaning', runId: 'run_1001', level: 'INFO', message: 'Pipeline run #run_1001 started via Hourly Scheduler.' },
];

export const INITIAL_TASKS: ProjectTask[] = [
  {
    id: 'task_101',
    projectId: 'proj_telemetry',
    title: 'Migrate Telemetry Schema to V3',
    description: 'Add match_mode field and make weapon_skin_id required for combat events',
    assigneeId: 'usr_alex',
    priority: 'high',
    status: 'in_progress',
    pipelineId: 'pipe_telemetry_clean',
    dueDate: '2026-09-05',
    subtasks: [
      { id: 'st_1', title: 'Update Schema Registry definition', completed: true },
      { id: 'st_2', title: 'Update Ingestion Filter node config', completed: false },
      { id: 'st_3', title: 'Run validation test suite', completed: false },
    ],
    createdAt: '2026-08-28T10:00:00Z',
  },
  {
    id: 'task_102',
    projectId: 'proj_economy',
    title: 'Audit IAP Purchase Contract SLA',
    description: 'Verify 99.9% freshness SLA with Finance team',
    assigneeId: 'usr_sarah',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-09-10',
    subtasks: [
      { id: 'st_11', title: 'Review SLA violation logs', completed: false },
    ],
    createdAt: '2026-08-30T11:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditEvent[] = [
  { id: 'aud_1', timestamp: '2026-08-31T20:00:00Z', userId: 'usr_alex', userName: 'Alex Vance', action: 'Pipeline executed', resourceType: 'pipeline', resourceId: 'pipe_telemetry_clean', details: 'Manual trigger of Raw Telemetry Ingestion & Cleaning' },
  { id: 'aud_2', timestamp: '2026-08-31T18:00:00Z', userId: 'usr_sarah', userName: 'Sarah Connor', action: 'Schema modified', resourceType: 'schema', resourceId: 'sch_game_event', details: 'Updated field "level" nullability to true' },
];
